version: '3'

services: 
  app:
    build: .
    container_name: appDjango
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/blitzkrieg/app

    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: appDjangoDB
    tty: true
    environment:
      - POSTGRES_DB=appDjango
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mudar__2022
    volumes:
      - appDjango-pgdata:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      container_name: addDjangoPgadmin
      tty: true
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@user.com
        - PGADMIN_DEFAULT_PASSWORD=suasenha_@321
      ports:
        - 7800:80

volumes:
  appDjango-pgdata:
    external: true
